In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [4]:
df = pd.read_csv('cleaned_data.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3448 entries, 0 to 3447
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   president              3448 non-null   object
 1   question_order         3448 non-null   int64 
 2   interview_question     3448 non-null   object
 3   interview_answer       3448 non-null   object
 4   question               3448 non-null   object
 5   inaudible              3448 non-null   bool  
 6   multiple_questions     3448 non-null   bool  
 7   affirmative_questions  3448 non-null   bool  
 8   index                  3448 non-null   int64 
 9   clarity_label          3448 non-null   object
 10  evasion_label          3448 non-null   object
dtypes: bool(3), int64(2), object(6)
memory usage: 225.7+ KB


In [5]:
TARGET_COLUMN = 'evasion_label'
df['question'] = df['question'].astype(str).fillna('')
df['interview_answer'] = df['interview_answer'].astype(str).fillna('')
df[TARGET_COLUMN] = df[TARGET_COLUMN].astype(str)

print(f"Classes distribution {TARGET_COLUMN}:")
print(df[TARGET_COLUMN].value_counts())

Classes distribution evasion_label:
evasion_label
Explicit               1052
Dodging                 706
Implicit                488
General                 386
Deflection              381
Declining to answer     145
Claims ignorance        119
Clarification            92
Partial/half-answer      79
Name: count, dtype: int64


In [6]:
df['text_input'] = df['question'] + " [SEP] " + df['interview_answer']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    df['text_input'],
    df[TARGET_COLUMN],
    test_size=0.2,
    random_state=42,
    stratify=df[TARGET_COLUMN]
)
vectorizer = TfidfVectorizer(max_features=5000)
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

In [8]:
model = LogisticRegression(max_iter=1000, class_weight='balanced')
model.fit(X_train_vec, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [9]:
preds = model.predict(X_test_vec)

print(f"Accuracy: {accuracy_score(y_test, preds):.4f}")
print("\nDetailed report (Precision, Recall, F1):")
print(classification_report(y_test, preds))

cm = confusion_matrix(y_test, preds)
print("\nConfusion Matrix:")
print(cm)

Accuracy: 0.2681

Detailed report (Precision, Recall, F1):
                     precision    recall  f1-score   support

   Claims ignorance       0.22      0.38      0.28        24
      Clarification       0.29      0.78      0.42        18
Declining to answer       0.20      0.34      0.25        29
         Deflection       0.19      0.29      0.23        76
            Dodging       0.30      0.22      0.25       141
           Explicit       0.49      0.23      0.32       211
            General       0.27      0.29      0.28        77
           Implicit       0.23      0.26      0.24        98
Partial/half-answer       0.08      0.19      0.12        16

           accuracy                           0.27       690
          macro avg       0.25      0.33      0.26       690
       weighted avg       0.32      0.27      0.27       690


Confusion Matrix:
[[ 9  1  2  3  4  2  0  2  1]
 [ 0 14  0  0  3  0  1  0  0]
 [ 1  5 10  4  3  1  2  1  2]
 [ 6  2  3 22 13  3  8 18  1]
 [ 7  

In [10]:
from sklearn import svm

svm_clf = svm.SVC(kernel='linear',class_weight='balanced', random_state=42)
svm_clf.fit(X_train_vec, y_train)

SVC(class_weight='balanced', kernel='linear', random_state=42)

In [11]:
preds = svm_clf.predict(X_test_vec)

print(f"Accuracy: {accuracy_score(y_test, preds):.4f}")
print("\nDetailed report (Precision, Recall, F1):")
print(classification_report(y_test, preds))

cm = confusion_matrix(y_test, preds)
print("\nConfusion Matrix:")
print(cm)

Accuracy: 0.2870

Detailed report (Precision, Recall, F1):
                     precision    recall  f1-score   support

   Claims ignorance       0.27      0.29      0.28        24
      Clarification       0.50      0.67      0.57        18
Declining to answer       0.30      0.31      0.31        29
         Deflection       0.19      0.34      0.24        76
            Dodging       0.29      0.26      0.27       141
           Explicit       0.52      0.25      0.34       211
            General       0.24      0.27      0.25        77
           Implicit       0.23      0.32      0.26        98
Partial/half-answer       0.13      0.19      0.15        16

           accuracy                           0.29       690
          macro avg       0.30      0.32      0.30       690
       weighted avg       0.34      0.29      0.29       690


Confusion Matrix:
[[ 7  1  1  4  6  2  0  2  1]
 [ 0 12  0  0  5  0  1  0  0]
 [ 0  0  9  4  7  3  2  2  2]
 [ 4  0  1 26 12  3 11 19  0]
 [ 8  